// Generated by dts-bundle-generator v9.5.1

declare const app: import("hono/hono-base").HonoBase<{}, {
	"*": {};
} | import("hono/types").MergeSchemaPath<({
	"/": {
		$get: {
			input: {};
			output: {
				id: string;
				name: string;
				capacity: number;
				items: number;
				max_weight: number;
				average_weirdness: number;
				weight: number;
			}[];
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/": {
		$post: {
			input: {
				json: {
					name: string;
					capacity: number;
					max_weight: number;
				};
			};
			output: {
				id: string;
				name: string;
				capacity: number;
				items: number;
				max_weight: number;
				average_weirdness: number;
				weight: number;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/:id": {
		$get: {
			input: {
				param: {
					id: string;
				};
			};
			output: {
				id: string;
				name: string;
				capacity: number;
				items: number;
				max_weight: number;
				average_weirdness: number;
				weight: number;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/:id": {
		$delete: {
			input: {
				param: {
					id: string;
				};
			};
			output: {
				id: string;
				name: string;
				capacity: number;
				items: number;
				max_weight: number;
				average_weirdness: number;
				weight: number;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
}) | import("hono/types").MergeSchemaPath<{
	"/:id/items": {
		$get: {
			input: {
				param: {
					id: string;
				};
			} & {
				query: {
					min?: string | string[] | undefined;
				};
			};
			output: {
				cuid: string;
				name: string;
				weightKg: number;
				weirdness: number;
				fragile: boolean;
			}[];
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/:id/items/:iid": {
		$get: {
			input: {
				param: {
					id: string;
					iid: string;
				};
			};
			output: {
				cuid: string;
				name: string;
				weightKg: number;
				weirdness: number;
				fragile: boolean;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/:id/items": {
		$post: {
			input: {
				json: {
					name: string;
					weirdness: number;
					fragile: boolean;
					weight_kg: number;
				};
			} & {
				param: {
					id: string;
				};
			};
			output: {
				message: string;
			};
			outputFormat: "json";
			status: 400;
		} | {
			input: {
				json: {
					name: string;
					weirdness: number;
					fragile: boolean;
					weight_kg: number;
				};
			} & {
				param: {
					id: string;
				};
			};
			output: {
				cuid: string;
				name: string;
				weightKg: number;
				weirdness: number;
				fragile: boolean;
			};
			outputFormat: "json";
			status: 200;
		};
	};
} & {
	"/:id/items/:iid": {
		$delete: {
			input: {
				param: {
					id: string;
					iid: string;
				};
			};
			output: {
				cuid: string;
				name: string;
				weightKg: number;
				weirdness: number;
				fragile: boolean;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
}, "/">, "/api/warehouses">, "/">;
export type MyApp = typeof app;

export {};
